#pragma once
#include <iostream>
#include <string>
#include <fstream>
using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::getline;
using std::fstream;
using std::ifstream;
using std::ostream;
using std::istream;
